branches:
  only:
  - master
  - /^greenkeeper/.*$/

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov coveralls

install:
  - npm i -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: "GeoJsonEditor"
      env: PACKAGE_LOCATION=packages/react-geojson-editor EXTRA_UPLOAD_COV=ci/upload-coverage.sh"
    - name: "Demo"
      env: PACKAGE_LOCATION=packages/react-geojson-editor-demo EXTRA_UPLOAD_COV=ci/na.sh
script: 
  - cd $PACKAGE_LOCATION
  - npm i
  - bash $EXTRA_NPM_INSTALLS # run only if script exists
  - npm test -- --coverage
  - npm run build

after_success:
  - bash $EXTRA_UPLOAD_COV # send coverage to analysis sites
