branches:
  only:
  - master
  - /^greenkeeper/.*$/

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  - npm i -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: "GeoJsonEditor"
      env: PACKAGE_LOCATION=packages/react-geojson-editor EXTRA_NPM_INSTALLS=ci/install-peer-dep.sh
    - name: "Demo"
      env: PACKAGE_LOCATION=packages/react-geojson-editor-demo EXTRA_NPM_INSTALLS=ci/na.sh
script: 
  - cd $PACKAGE_LOCATION
  - npm i
  - echo "$EXTRA_NPM_INSTALLS" # run only if script exists
  - bash $EXTRA_NPM_INSTALLS # run only if script exists
  - npm test -- --coverage
  - npm run build
