branches:
  only:
  - master
  - /^greenkeeper/.*$/

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_install:
  - npm install -g codecov.io coveralls

install:
  - npm i -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: "GeoJsonEditor"
      env: PACKAGE_LOCATION=packages/react-geojson-editor EXTRA_NPM_INSTALLS=ci/install-peer-dep.sh CODECOV_TOKEN="66f7d8f9-3766-4ea6-ac36-9a901e0d65a2"
    - name: "Demo"
      env: PACKAGE_LOCATION=packages/react-geojson-editor-demo EXTRA_NPM_INSTALLS=ci/na.sh
script: 
  - cd $PACKAGE_LOCATION
  - npm i
  - echo "$EXTRA_NPM_INSTALLS" # run only if script exists
  - bash $EXTRA_NPM_INSTALLS # run only if script exists
  - npm test -- --coverage
  - npm run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
